import {
  faHome,
  faChartBar,
  faTrophy,
  faCalendar,
  faMap,
  faRobot,
  faNewspaper,
  faFlask,
  faFileLines,
  faPenToSquare,
  faGlobe,
  faComments,
  faThumbtack,
  faMagnifyingGlass,
  faStar as faStarSolid,
  faLightbulb,
  faFire,
  faBookOpen,
  faInbox,
  faChartPie,
  faSatelliteDish,
  faArrowTrendUp,
  faTags,
  faRocket,
  faArrowTrendDown,
  faArrowRight,
  faChevronDown,
  type IconDefinition,
} from '@fortawesome/free-solid-svg-icons'

/** Category icon mapping */
export const CATEGORY_ICONS: Record<string, IconDefinition> = {
  'AI Lab': faFlask,
  'Paper': faFileLines,
  '中文媒体': faGlobe,
  'Blog': faPenToSquare,
  'Community': faComments,
  'Discussion': faComments,
}
export const DEFAULT_CATEGORY_ICON = faThumbtack

/** Nav / header icons */
export const ICON = {
  home: faHome,
  dashboard: faChartPie,
  leaderboard: faTrophy,
  timeline: faCalendar,
  clusters: faMap,
  robot: faRobot,
  weekly: faNewspaper,
  search: faMagnifyingGlass,
  star: faStarSolid,
  lightbulb: faLightbulb,
  fire: faFire,
  bookOpen: faBookOpen,
  inbox: faInbox,
  chartBar: faChartBar,
  satelliteDish: faSatelliteDish,
  trendUp: faArrowTrendUp,
  tags: faTags,
  rocket: faRocket,
  trendDown: faArrowTrendDown,
  arrowRight: faArrowRight,
  chevronDown: faChevronDown,
  fileLines: faFileLines,
  paper: faFileLines,
  news: faNewspaper,
  globe: faGlobe,
  comments: faComments,
  pen: faPenToSquare,
  flask: faFlask,
  thumbtack: faThumbtack,
} as const

export type IconName = keyof typeof ICON
